# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BafangConfigTool.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 831)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Iconshock-Global-Warming-Bicycle.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelMade = QtWidgets.QLabel(self.centralwidget)
        self.labelMade.setGeometry(QtCore.QRect(670, 50, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMade.setFont(font)
        self.labelMade.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelMade.setObjectName("labelMade")
        self.pushButtonReadAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReadAll.setEnabled(False)
        self.pushButtonReadAll.setGeometry(QtCore.QRect(660, 670, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonReadAll.setFont(font)
        self.pushButtonReadAll.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonReadAll.setObjectName("pushButtonReadAll")
        self.comboBoxPorts = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPorts.setGeometry(QtCore.QRect(660, 160, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxPorts.setFont(font)
        self.comboBoxPorts.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.comboBoxPorts.setObjectName("comboBoxPorts")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 631, 781))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.tabWidget.setObjectName("tabWidget")
        self.tabBasic = QtWidgets.QWidget()
        self.tabBasic.setObjectName("tabBasic")
        self.label = QtWidgets.QLabel(self.tabBasic)
        self.label.setGeometry(QtCore.QRect(20, 20, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabBasic)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tabBasic)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tabBasic)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tabBasic)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tabBasic)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.spinBoxCurrentLimit = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxCurrentLimit.setGeometry(QtCore.QRect(250, 60, 91, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxCurrentLimit.setFont(font)
        self.spinBoxCurrentLimit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxCurrentLimit.setProperty("value", 15)
        self.spinBoxCurrentLimit.setObjectName("spinBoxCurrentLimit")
        self.spinBoxAssist0 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist0.setGeometry(QtCore.QRect(210, 170, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist0.setFont(font)
        self.spinBoxAssist0.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist0.setMaximum(100)
        self.spinBoxAssist0.setProperty("value", 10)
        self.spinBoxAssist0.setObjectName("spinBoxAssist0")
        self.spinBoxAssist1 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist1.setGeometry(QtCore.QRect(210, 210, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist1.setFont(font)
        self.spinBoxAssist1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist1.setMaximum(100)
        self.spinBoxAssist1.setProperty("value", 20)
        self.spinBoxAssist1.setObjectName("spinBoxAssist1")
        self.spinBoxAssist2 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist2.setGeometry(QtCore.QRect(210, 250, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist2.setFont(font)
        self.spinBoxAssist2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist2.setMaximum(100)
        self.spinBoxAssist2.setProperty("value", 30)
        self.spinBoxAssist2.setObjectName("spinBoxAssist2")
        self.spinBoxAssist3 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist3.setGeometry(QtCore.QRect(210, 290, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist3.setFont(font)
        self.spinBoxAssist3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist3.setMaximum(100)
        self.spinBoxAssist3.setProperty("value", 40)
        self.spinBoxAssist3.setObjectName("spinBoxAssist3")
        self.label_7 = QtWidgets.QLabel(self.tabBasic)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tabBasic)
        self.label_8.setGeometry(QtCore.QRect(20, 410, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tabBasic)
        self.label_9.setGeometry(QtCore.QRect(20, 370, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.spinBoxAssist6 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist6.setGeometry(QtCore.QRect(210, 410, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist6.setFont(font)
        self.spinBoxAssist6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist6.setMaximum(100)
        self.spinBoxAssist6.setProperty("value", 70)
        self.spinBoxAssist6.setObjectName("spinBoxAssist6")
        self.spinBoxAssist5 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist5.setGeometry(QtCore.QRect(210, 370, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist5.setFont(font)
        self.spinBoxAssist5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist5.setMaximum(100)
        self.spinBoxAssist5.setProperty("value", 60)
        self.spinBoxAssist5.setObjectName("spinBoxAssist5")
        self.label_10 = QtWidgets.QLabel(self.tabBasic)
        self.label_10.setGeometry(QtCore.QRect(20, 330, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tabBasic)
        self.label_11.setGeometry(QtCore.QRect(20, 450, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.spinBoxAssist4 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist4.setGeometry(QtCore.QRect(210, 330, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist4.setFont(font)
        self.spinBoxAssist4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist4.setMaximum(100)
        self.spinBoxAssist4.setProperty("value", 50)
        self.spinBoxAssist4.setObjectName("spinBoxAssist4")
        self.spinBoxAssist7 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist7.setGeometry(QtCore.QRect(210, 450, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist7.setFont(font)
        self.spinBoxAssist7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist7.setMaximum(100)
        self.spinBoxAssist7.setProperty("value", 80)
        self.spinBoxAssist7.setObjectName("spinBoxAssist7")
        self.label_13 = QtWidgets.QLabel(self.tabBasic)
        self.label_13.setGeometry(QtCore.QRect(20, 490, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.spinBoxAssist9 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist9.setGeometry(QtCore.QRect(210, 530, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist9.setFont(font)
        self.spinBoxAssist9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist9.setMaximum(100)
        self.spinBoxAssist9.setProperty("value", 100)
        self.spinBoxAssist9.setObjectName("spinBoxAssist9")
        self.label_14 = QtWidgets.QLabel(self.tabBasic)
        self.label_14.setGeometry(QtCore.QRect(20, 530, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.spinBoxAssist8 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxAssist8.setGeometry(QtCore.QRect(210, 490, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxAssist8.setFont(font)
        self.spinBoxAssist8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist8.setMaximum(100)
        self.spinBoxAssist8.setProperty("value", 90)
        self.spinBoxAssist8.setObjectName("spinBoxAssist8")
        self.label_12 = QtWidgets.QLabel(self.tabBasic)
        self.label_12.setGeometry(QtCore.QRect(200, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.spinBoxSpeedlimit9 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit9.setGeometry(QtCore.QRect(410, 530, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit9.setFont(font)
        self.spinBoxSpeedlimit9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit9.setMaximum(100)
        self.spinBoxSpeedlimit9.setProperty("value", 100)
        self.spinBoxSpeedlimit9.setObjectName("spinBoxSpeedlimit9")
        self.spinBoxSpeedlimit2 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit2.setGeometry(QtCore.QRect(410, 250, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit2.setFont(font)
        self.spinBoxSpeedlimit2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit2.setMaximum(100)
        self.spinBoxSpeedlimit2.setProperty("value", 30)
        self.spinBoxSpeedlimit2.setObjectName("spinBoxSpeedlimit2")
        self.spinBoxSpeedlimit1 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit1.setGeometry(QtCore.QRect(410, 210, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit1.setFont(font)
        self.spinBoxSpeedlimit1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit1.setMaximum(100)
        self.spinBoxSpeedlimit1.setProperty("value", 20)
        self.spinBoxSpeedlimit1.setObjectName("spinBoxSpeedlimit1")
        self.spinBoxSpeedlimit6 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit6.setGeometry(QtCore.QRect(410, 410, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit6.setFont(font)
        self.spinBoxSpeedlimit6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit6.setMaximum(100)
        self.spinBoxSpeedlimit6.setProperty("value", 70)
        self.spinBoxSpeedlimit6.setObjectName("spinBoxSpeedlimit6")
        self.spinBoxSpeedlimit7 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit7.setGeometry(QtCore.QRect(410, 450, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit7.setFont(font)
        self.spinBoxSpeedlimit7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit7.setMaximum(100)
        self.spinBoxSpeedlimit7.setProperty("value", 80)
        self.spinBoxSpeedlimit7.setObjectName("spinBoxSpeedlimit7")
        self.label_15 = QtWidgets.QLabel(self.tabBasic)
        self.label_15.setGeometry(QtCore.QRect(410, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.spinBoxSpeedlimit8 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit8.setGeometry(QtCore.QRect(410, 490, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit8.setFont(font)
        self.spinBoxSpeedlimit8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit8.setMaximum(100)
        self.spinBoxSpeedlimit8.setProperty("value", 90)
        self.spinBoxSpeedlimit8.setObjectName("spinBoxSpeedlimit8")
        self.spinBoxSpeedlimit4 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit4.setGeometry(QtCore.QRect(410, 330, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit4.setFont(font)
        self.spinBoxSpeedlimit4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit4.setMaximum(100)
        self.spinBoxSpeedlimit4.setProperty("value", 50)
        self.spinBoxSpeedlimit4.setObjectName("spinBoxSpeedlimit4")
        self.spinBoxSpeedlimit5 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit5.setGeometry(QtCore.QRect(410, 370, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit5.setFont(font)
        self.spinBoxSpeedlimit5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit5.setMaximum(100)
        self.spinBoxSpeedlimit5.setProperty("value", 60)
        self.spinBoxSpeedlimit5.setObjectName("spinBoxSpeedlimit5")
        self.spinBoxSpeedlimit0 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit0.setGeometry(QtCore.QRect(410, 170, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit0.setFont(font)
        self.spinBoxSpeedlimit0.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit0.setMaximum(100)
        self.spinBoxSpeedlimit0.setProperty("value", 10)
        self.spinBoxSpeedlimit0.setObjectName("spinBoxSpeedlimit0")
        self.spinBoxSpeedlimit3 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedlimit3.setGeometry(QtCore.QRect(410, 290, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedlimit3.setFont(font)
        self.spinBoxSpeedlimit3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit3.setMaximum(100)
        self.spinBoxSpeedlimit3.setProperty("value", 40)
        self.spinBoxSpeedlimit3.setObjectName("spinBoxSpeedlimit3")
        self.spinBoxLowBatteryVoltage = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxLowBatteryVoltage.setEnabled(True)
        self.spinBoxLowBatteryVoltage.setGeometry(QtCore.QRect(250, 20, 91, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxLowBatteryVoltage.setFont(font)
        self.spinBoxLowBatteryVoltage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxLowBatteryVoltage.setProperty("value", 30)
        self.spinBoxLowBatteryVoltage.setObjectName("spinBoxLowBatteryVoltage")
        self.label_16 = QtWidgets.QLabel(self.tabBasic)
        self.label_16.setGeometry(QtCore.QRect(20, 590, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.tabBasic)
        self.label_18.setGeometry(QtCore.QRect(20, 640, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tabBasic)
        self.label_19.setGeometry(QtCore.QRect(20, 690, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.comboBoxPorts_2 = QtWidgets.QComboBox(self.tabBasic)
        self.comboBoxPorts_2.setGeometry(QtCore.QRect(210, 580, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxPorts_2.setFont(font)
        self.comboBoxPorts_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.comboBoxPorts_2.setObjectName("comboBoxPorts_2")
        self.comboBoxPorts_2.addItem("")
        self.comboBoxPorts_2.addItem("")
        self.comboBoxPorts_2.addItem("")
        self.comboBoxPorts_3 = QtWidgets.QComboBox(self.tabBasic)
        self.comboBoxPorts_3.setGeometry(QtCore.QRect(210, 680, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxPorts_3.setFont(font)
        self.comboBoxPorts_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.comboBoxPorts_3.setObjectName("comboBoxPorts_3")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.comboBoxPorts_3.addItem("")
        self.spinBoxSpeedMeterSignals = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpeedMeterSignals.setGeometry(QtCore.QRect(210, 640, 131, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxSpeedMeterSignals.setFont(font)
        self.spinBoxSpeedMeterSignals.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedMeterSignals.setMaximum(100)
        self.spinBoxSpeedMeterSignals.setProperty("value", 1)
        self.spinBoxSpeedMeterSignals.setObjectName("spinBoxSpeedMeterSignals")
        self.pushButtonRead = QtWidgets.QPushButton(self.tabBasic)
        self.pushButtonRead.setEnabled(False)
        self.pushButtonRead.setGeometry(QtCore.QRect(420, 630, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonRead.setFont(font)
        self.pushButtonRead.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonRead.setObjectName("pushButtonRead")
        self.pushButtonWrite = QtWidgets.QPushButton(self.tabBasic)
        self.pushButtonWrite.setEnabled(False)
        self.pushButtonWrite.setGeometry(QtCore.QRect(420, 680, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonWrite.setFont(font)
        self.pushButtonWrite.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonWrite.setObjectName("pushButtonWrite")
        self.tabWidget.addTab(self.tabBasic, "")
        self.tabPedal = QtWidgets.QWidget()
        self.tabPedal.setObjectName("tabPedal")
        self.tabWidget.addTab(self.tabPedal, "")
        self.tabThrottle = QtWidgets.QWidget()
        self.tabThrottle.setObjectName("tabThrottle")
        self.tabWidget.addTab(self.tabThrottle, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(660, 250, 341, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.groupBox.setObjectName("groupBox")
        self.labelManufacturer = QtWidgets.QLabel(self.groupBox)
        self.labelManufacturer.setGeometry(QtCore.QRect(20, 50, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelManufacturer.setFont(font)
        self.labelManufacturer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelManufacturer.setObjectName("labelManufacturer")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(340, 60, 311, 16))
        self.label_17.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_17.setObjectName("label_17")
        self.labelModel = QtWidgets.QLabel(self.groupBox)
        self.labelModel.setGeometry(QtCore.QRect(20, 90, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelModel.setFont(font)
        self.labelModel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelModel.setObjectName("labelModel")
        self.labelHardwVers = QtWidgets.QLabel(self.groupBox)
        self.labelHardwVers.setGeometry(QtCore.QRect(20, 130, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHardwVers.setFont(font)
        self.labelHardwVers.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelHardwVers.setObjectName("labelHardwVers")
        self.labelFirmVers = QtWidgets.QLabel(self.groupBox)
        self.labelFirmVers.setGeometry(QtCore.QRect(20, 170, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFirmVers.setFont(font)
        self.labelFirmVers.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelFirmVers.setObjectName("labelFirmVers")
        self.labelMaxCurrent = QtWidgets.QLabel(self.groupBox)
        self.labelMaxCurrent.setGeometry(QtCore.QRect(20, 250, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxCurrent.setFont(font)
        self.labelMaxCurrent.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelMaxCurrent.setObjectName("labelMaxCurrent")
        self.labelModel_2 = QtWidgets.QLabel(self.groupBox)
        self.labelModel_2.setGeometry(QtCore.QRect(200, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelModel_2.setFont(font)
        self.labelModel_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelModel_2.setObjectName("labelModel_2")
        self.labelFirmVers_2 = QtWidgets.QLabel(self.groupBox)
        self.labelFirmVers_2.setGeometry(QtCore.QRect(200, 170, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFirmVers_2.setFont(font)
        self.labelFirmVers_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelFirmVers_2.setObjectName("labelFirmVers_2")
        self.labelHardwVers_2 = QtWidgets.QLabel(self.groupBox)
        self.labelHardwVers_2.setGeometry(QtCore.QRect(200, 130, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHardwVers_2.setFont(font)
        self.labelHardwVers_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelHardwVers_2.setObjectName("labelHardwVers_2")
        self.labelMaxCurrent_2 = QtWidgets.QLabel(self.groupBox)
        self.labelMaxCurrent_2.setGeometry(QtCore.QRect(200, 250, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxCurrent_2.setFont(font)
        self.labelMaxCurrent_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelMaxCurrent_2.setObjectName("labelMaxCurrent_2")
        self.labelManufacturer_2 = QtWidgets.QLabel(self.groupBox)
        self.labelManufacturer_2.setGeometry(QtCore.QRect(200, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelManufacturer_2.setFont(font)
        self.labelManufacturer_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelManufacturer_2.setObjectName("labelManufacturer_2")
        self.labelNominalVoltage = QtWidgets.QLabel(self.groupBox)
        self.labelNominalVoltage.setGeometry(QtCore.QRect(20, 210, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNominalVoltage.setFont(font)
        self.labelNominalVoltage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelNominalVoltage.setObjectName("labelNominalVoltage")
        self.labelNominalVoltage_2 = QtWidgets.QLabel(self.groupBox)
        self.labelNominalVoltage_2.setGeometry(QtCore.QRect(200, 210, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNominalVoltage_2.setFont(font)
        self.labelNominalVoltage_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelNominalVoltage_2.setObjectName("labelNominalVoltage_2")
        self.pushButtonScan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonScan.setGeometry(QtCore.QRect(950, 160, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonScan.setFont(font)
        self.pushButtonScan.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonScan.setObjectName("pushButtonScan")
        self.pushButtonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonConnect.setEnabled(False)
        self.pushButtonConnect.setGeometry(QtCore.QRect(660, 110, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonConnect.setFont(font)
        self.pushButtonConnect.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDisconnect.setEnabled(False)
        self.pushButtonDisconnect.setGeometry(QtCore.QRect(830, 110, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonDisconnect.setFont(font)
        self.pushButtonDisconnect.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setCheckable(False)
        self.actionHelp.setChecked(False)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxPorts_3.setCurrentIndex(10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bafang Configuration Tool"))
        self.labelMade.setText(_translate("MainWindow", "Made by Charclo"))
        self.pushButtonReadAll.setText(_translate("MainWindow", "READ ALL"))
        self.label.setText(_translate("MainWindow", "Low Battery Protection (V):"))
        self.label_2.setText(_translate("MainWindow", "Current Limit (A):"))
        self.label_3.setText(_translate("MainWindow", "Assist 0:"))
        self.label_4.setText(_translate("MainWindow", "Assist 1:"))
        self.label_5.setText(_translate("MainWindow", "Assist 2:"))
        self.label_6.setText(_translate("MainWindow", "Assist 3:"))
        self.label_7.setText(_translate("MainWindow", "Assist Levels"))
        self.label_8.setText(_translate("MainWindow", "Assist 6:"))
        self.label_9.setText(_translate("MainWindow", "Assist 5:"))
        self.label_10.setText(_translate("MainWindow", "Assist 4:"))
        self.label_11.setText(_translate("MainWindow", "Assist 7:"))
        self.label_13.setText(_translate("MainWindow", "Assist 8:"))
        self.label_14.setText(_translate("MainWindow", "Assist 9:"))
        self.label_12.setText(_translate("MainWindow", "Current limit (%)"))
        self.label_15.setText(_translate("MainWindow", "Speed limit (%)"))
        self.label_16.setText(_translate("MainWindow", "Speed meter type:"))
        self.label_18.setText(_translate("MainWindow", "Speed Meter Signals:"))
        self.label_19.setText(_translate("MainWindow", "Wheel diameter (Inch):"))
        self.comboBoxPorts_2.setItemText(0, _translate("MainWindow", "External, wheel meter"))
        self.comboBoxPorts_2.setItemText(1, _translate("MainWindow", "Internal, motor meter"))
        self.comboBoxPorts_2.setItemText(2, _translate("MainWindow", "By motor phase"))
        self.comboBoxPorts_3.setCurrentText(_translate("MainWindow", "26"))
        self.comboBoxPorts_3.setItemText(0, _translate("MainWindow", "16"))
        self.comboBoxPorts_3.setItemText(1, _translate("MainWindow", "17"))
        self.comboBoxPorts_3.setItemText(2, _translate("MainWindow", "18"))
        self.comboBoxPorts_3.setItemText(3, _translate("MainWindow", "19"))
        self.comboBoxPorts_3.setItemText(4, _translate("MainWindow", "20"))
        self.comboBoxPorts_3.setItemText(5, _translate("MainWindow", "21"))
        self.comboBoxPorts_3.setItemText(6, _translate("MainWindow", "22"))
        self.comboBoxPorts_3.setItemText(7, _translate("MainWindow", "23"))
        self.comboBoxPorts_3.setItemText(8, _translate("MainWindow", "24"))
        self.comboBoxPorts_3.setItemText(9, _translate("MainWindow", "25"))
        self.comboBoxPorts_3.setItemText(10, _translate("MainWindow", "26"))
        self.comboBoxPorts_3.setItemText(11, _translate("MainWindow", "27"))
        self.comboBoxPorts_3.setItemText(12, _translate("MainWindow", "700C"))
        self.comboBoxPorts_3.setItemText(13, _translate("MainWindow", "28"))
        self.comboBoxPorts_3.setItemText(14, _translate("MainWindow", "29"))
        self.comboBoxPorts_3.setItemText(15, _translate("MainWindow", "30"))
        self.pushButtonRead.setText(_translate("MainWindow", "READ"))
        self.pushButtonWrite.setText(_translate("MainWindow", "WRITE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBasic), _translate("MainWindow", "Basic"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPedal), _translate("MainWindow", "Pedal Assist"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabThrottle), _translate("MainWindow", "Throttle Handle"))
        self.groupBox.setTitle(_translate("MainWindow", "Controller Info"))
        self.labelManufacturer.setText(_translate("MainWindow", "Manufacturer:"))
        self.label_17.setText(_translate("MainWindow", "Manufacturer:"))
        self.labelModel.setText(_translate("MainWindow", "Model:"))
        self.labelHardwVers.setText(_translate("MainWindow", "Hardware version:"))
        self.labelFirmVers.setText(_translate("MainWindow", "Firmware version:"))
        self.labelMaxCurrent.setText(_translate("MainWindow", "Max. Current:"))
        self.labelModel_2.setText(_translate("MainWindow", "N/A"))
        self.labelFirmVers_2.setText(_translate("MainWindow", "N/A"))
        self.labelHardwVers_2.setText(_translate("MainWindow", "N/A"))
        self.labelMaxCurrent_2.setText(_translate("MainWindow", "N/A"))
        self.labelManufacturer_2.setText(_translate("MainWindow", "N/A"))
        self.labelNominalVoltage.setText(_translate("MainWindow", "Nominal voltage:"))
        self.labelNominalVoltage_2.setText(_translate("MainWindow", "N/A"))
        self.pushButtonScan.setText(_translate("MainWindow", "Scan"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.pushButtonDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad.setText(_translate("MainWindow", "Load configuration"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionSave.setText(_translate("MainWindow", "Save configuration"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
