# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BafangConfigTool.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 831)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Iconshock-Global-Warming-Bicycle.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelMade = QtWidgets.QLabel(self.centralwidget)
        self.labelMade.setGeometry(QtCore.QRect(660, 80, 161, 41))
        self.labelMade.setObjectName("labelMade")
        self.pushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoad.setGeometry(QtCore.QRect(660, 200, 161, 41))
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.comboBoxPorts = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPorts.setGeometry(QtCore.QRect(660, 140, 161, 41))
        self.comboBoxPorts.setObjectName("comboBoxPorts")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 631, 781))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBasic = QtWidgets.QWidget()
        self.tabBasic.setObjectName("tabBasic")
        self.label = QtWidgets.QLabel(self.tabBasic)
        self.label.setGeometry(QtCore.QRect(20, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabBasic)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tabBasic)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tabBasic)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tabBasic)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tabBasic)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.spinBox = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox.setGeometry(QtCore.QRect(230, 60, 61, 22))
        self.spinBox.setProperty("value", 20)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_2.setGeometry(QtCore.QRect(210, 170, 131, 22))
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setProperty("value", 10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_3.setGeometry(QtCore.QRect(210, 210, 131, 22))
        self.spinBox_3.setMaximum(100)
        self.spinBox_3.setProperty("value", 20)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_4.setGeometry(QtCore.QRect(210, 250, 131, 22))
        self.spinBox_4.setMaximum(100)
        self.spinBox_4.setProperty("value", 30)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_5.setGeometry(QtCore.QRect(210, 290, 131, 22))
        self.spinBox_5.setMaximum(100)
        self.spinBox_5.setProperty("value", 40)
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_7 = QtWidgets.QLabel(self.tabBasic)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tabBasic)
        self.label_8.setGeometry(QtCore.QRect(20, 410, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tabBasic)
        self.label_9.setGeometry(QtCore.QRect(20, 370, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.spinBox_6 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_6.setGeometry(QtCore.QRect(210, 410, 131, 22))
        self.spinBox_6.setMaximum(100)
        self.spinBox_6.setProperty("value", 70)
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_7.setGeometry(QtCore.QRect(210, 370, 131, 22))
        self.spinBox_7.setMaximum(100)
        self.spinBox_7.setProperty("value", 60)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_10 = QtWidgets.QLabel(self.tabBasic)
        self.label_10.setGeometry(QtCore.QRect(20, 330, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tabBasic)
        self.label_11.setGeometry(QtCore.QRect(20, 450, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.spinBox_8 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_8.setGeometry(QtCore.QRect(210, 330, 131, 22))
        self.spinBox_8.setMaximum(100)
        self.spinBox_8.setProperty("value", 50)
        self.spinBox_8.setObjectName("spinBox_8")
        self.spinBox_9 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_9.setGeometry(QtCore.QRect(210, 450, 131, 22))
        self.spinBox_9.setMaximum(100)
        self.spinBox_9.setProperty("value", 80)
        self.spinBox_9.setObjectName("spinBox_9")
        self.label_13 = QtWidgets.QLabel(self.tabBasic)
        self.label_13.setGeometry(QtCore.QRect(20, 490, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.spinBox_10 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_10.setGeometry(QtCore.QRect(210, 530, 131, 22))
        self.spinBox_10.setMaximum(100)
        self.spinBox_10.setProperty("value", 100)
        self.spinBox_10.setObjectName("spinBox_10")
        self.label_14 = QtWidgets.QLabel(self.tabBasic)
        self.label_14.setGeometry(QtCore.QRect(20, 530, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.spinBox_12 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_12.setGeometry(QtCore.QRect(210, 490, 131, 22))
        self.spinBox_12.setMaximum(100)
        self.spinBox_12.setProperty("value", 90)
        self.spinBox_12.setObjectName("spinBox_12")
        self.label_12 = QtWidgets.QLabel(self.tabBasic)
        self.label_12.setGeometry(QtCore.QRect(200, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.spinBoxSpLimit9 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBoxSpLimit9.setGeometry(QtCore.QRect(410, 530, 131, 22))
        self.spinBoxSpLimit9.setMaximum(100)
        self.spinBoxSpLimit9.setProperty("value", 100)
        self.spinBoxSpLimit9.setObjectName("spinBoxSpLimit9")
        self.spinBox_13 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_13.setGeometry(QtCore.QRect(410, 250, 131, 22))
        self.spinBox_13.setMaximum(100)
        self.spinBox_13.setProperty("value", 30)
        self.spinBox_13.setObjectName("spinBox_13")
        self.spinBox_14 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_14.setGeometry(QtCore.QRect(410, 210, 131, 22))
        self.spinBox_14.setMaximum(100)
        self.spinBox_14.setProperty("value", 20)
        self.spinBox_14.setObjectName("spinBox_14")
        self.spinBox_15 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_15.setGeometry(QtCore.QRect(410, 410, 131, 22))
        self.spinBox_15.setMaximum(100)
        self.spinBox_15.setProperty("value", 70)
        self.spinBox_15.setObjectName("spinBox_15")
        self.spinBox_16 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_16.setGeometry(QtCore.QRect(410, 450, 131, 22))
        self.spinBox_16.setMaximum(100)
        self.spinBox_16.setProperty("value", 80)
        self.spinBox_16.setObjectName("spinBox_16")
        self.label_15 = QtWidgets.QLabel(self.tabBasic)
        self.label_15.setGeometry(QtCore.QRect(410, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.spinBox_17 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_17.setGeometry(QtCore.QRect(410, 490, 131, 22))
        self.spinBox_17.setMaximum(100)
        self.spinBox_17.setProperty("value", 90)
        self.spinBox_17.setObjectName("spinBox_17")
        self.spinBox_18 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_18.setGeometry(QtCore.QRect(410, 330, 131, 22))
        self.spinBox_18.setMaximum(100)
        self.spinBox_18.setProperty("value", 50)
        self.spinBox_18.setObjectName("spinBox_18")
        self.spinBox_19 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_19.setGeometry(QtCore.QRect(410, 370, 131, 22))
        self.spinBox_19.setMaximum(100)
        self.spinBox_19.setProperty("value", 60)
        self.spinBox_19.setObjectName("spinBox_19")
        self.spinBox_20 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_20.setGeometry(QtCore.QRect(410, 170, 131, 22))
        self.spinBox_20.setMaximum(100)
        self.spinBox_20.setProperty("value", 10)
        self.spinBox_20.setObjectName("spinBox_20")
        self.spinBox_21 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_21.setGeometry(QtCore.QRect(410, 290, 131, 22))
        self.spinBox_21.setMaximum(100)
        self.spinBox_21.setProperty("value", 40)
        self.spinBox_21.setObjectName("spinBox_21")
        self.spinBox_43 = QtWidgets.QSpinBox(self.tabBasic)
        self.spinBox_43.setEnabled(True)
        self.spinBox_43.setGeometry(QtCore.QRect(230, 20, 61, 22))
        self.spinBox_43.setProperty("value", 30)
        self.spinBox_43.setObjectName("spinBox_43")
        self.tabWidget.addTab(self.tabBasic, "")
        self.tabPedal = QtWidgets.QWidget()
        self.tabPedal.setObjectName("tabPedal")
        self.tabWidget.addTab(self.tabPedal, "")
        self.tabThrottle = QtWidgets.QWidget()
        self.tabThrottle.setObjectName("tabThrottle")
        self.tabWidget.addTab(self.tabThrottle, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(660, 320, 341, 261))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.labelManufacturer = QtWidgets.QLabel(self.groupBox)
        self.labelManufacturer.setGeometry(QtCore.QRect(20, 50, 111, 16))
        self.labelManufacturer.setObjectName("labelManufacturer")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(340, 60, 311, 16))
        self.label_17.setObjectName("label_17")
        self.labelModel = QtWidgets.QLabel(self.groupBox)
        self.labelModel.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.labelModel.setObjectName("labelModel")
        self.labelHardwVers = QtWidgets.QLabel(self.groupBox)
        self.labelHardwVers.setGeometry(QtCore.QRect(20, 130, 111, 16))
        self.labelHardwVers.setObjectName("labelHardwVers")
        self.labelFirmVers = QtWidgets.QLabel(self.groupBox)
        self.labelFirmVers.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.labelFirmVers.setObjectName("labelFirmVers")
        self.labelMaxCurrent = QtWidgets.QLabel(self.groupBox)
        self.labelMaxCurrent.setGeometry(QtCore.QRect(20, 210, 111, 16))
        self.labelMaxCurrent.setObjectName("labelMaxCurrent")
        self.labelModel_2 = QtWidgets.QLabel(self.groupBox)
        self.labelModel_2.setGeometry(QtCore.QRect(160, 90, 111, 16))
        self.labelModel_2.setObjectName("labelModel_2")
        self.labelFirmVers_2 = QtWidgets.QLabel(self.groupBox)
        self.labelFirmVers_2.setGeometry(QtCore.QRect(160, 170, 111, 16))
        self.labelFirmVers_2.setObjectName("labelFirmVers_2")
        self.labelHardwVers_2 = QtWidgets.QLabel(self.groupBox)
        self.labelHardwVers_2.setGeometry(QtCore.QRect(160, 130, 111, 16))
        self.labelHardwVers_2.setObjectName("labelHardwVers_2")
        self.labelMaxCurrent_2 = QtWidgets.QLabel(self.groupBox)
        self.labelMaxCurrent_2.setGeometry(QtCore.QRect(160, 210, 111, 16))
        self.labelMaxCurrent_2.setObjectName("labelMaxCurrent_2")
        self.labelManufacturer_2 = QtWidgets.QLabel(self.groupBox)
        self.labelManufacturer_2.setGeometry(QtCore.QRect(160, 50, 111, 16))
        self.labelManufacturer_2.setObjectName("labelManufacturer_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp_file = QtWidgets.QAction(MainWindow)
        self.actionHelp_file.setObjectName("actionHelp_file")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp_file)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bafang Configuration Tool"))
        self.labelMade.setText(_translate("MainWindow", "Made by Charclo"))
        self.pushButtonLoad.setText(_translate("MainWindow", "Load Info"))
        self.label.setText(_translate("MainWindow", "Low Battery Protection (V):"))
        self.label_2.setText(_translate("MainWindow", "Current Limit (A):"))
        self.label_3.setText(_translate("MainWindow", "Assist 0:"))
        self.label_4.setText(_translate("MainWindow", "Assist 1:"))
        self.label_5.setText(_translate("MainWindow", "Assist 2:"))
        self.label_6.setText(_translate("MainWindow", "Assist 3:"))
        self.label_7.setText(_translate("MainWindow", "Assist Levels"))
        self.label_8.setText(_translate("MainWindow", "Assist 6:"))
        self.label_9.setText(_translate("MainWindow", "Assist 5:"))
        self.label_10.setText(_translate("MainWindow", "Assist 4:"))
        self.label_11.setText(_translate("MainWindow", "Assist 7:"))
        self.label_13.setText(_translate("MainWindow", "Assist 8:"))
        self.label_14.setText(_translate("MainWindow", "Assist 9:"))
        self.label_12.setText(_translate("MainWindow", "Current limit (%)"))
        self.label_15.setText(_translate("MainWindow", "Speed limit (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBasic), _translate("MainWindow", "Basic"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPedal), _translate("MainWindow", "Pedal Assist"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabThrottle), _translate("MainWindow", "Throttle Handle"))
        self.groupBox.setTitle(_translate("MainWindow", "Controller Info"))
        self.labelManufacturer.setText(_translate("MainWindow", "Manufacturer:"))
        self.label_17.setText(_translate("MainWindow", "Manufacturer:"))
        self.labelModel.setText(_translate("MainWindow", "Model:"))
        self.labelHardwVers.setText(_translate("MainWindow", "Hardware version:"))
        self.labelFirmVers.setText(_translate("MainWindow", "Firmware version:"))
        self.labelMaxCurrent.setText(_translate("MainWindow", "Max. Current:"))
        self.labelModel_2.setText(_translate("MainWindow", "N/A"))
        self.labelFirmVers_2.setText(_translate("MainWindow", "N/A"))
        self.labelHardwVers_2.setText(_translate("MainWindow", "N/A"))
        self.labelMaxCurrent_2.setText(_translate("MainWindow", "N/A"))
        self.labelManufacturer_2.setText(_translate("MainWindow", "N/A"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad.setText(_translate("MainWindow", "Load configuration"))
        self.actionSave.setText(_translate("MainWindow", "Save configuration"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHelp_file.setText(_translate("MainWindow", "Help file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
